### ISSUE TITLE
使用Docker无法运行

### ISSUE THREAD

**Issue by BleethNie** [binzhouchn/masr#11]
1.运行环境
win10+docker desktop 3.2.2

2.运行步骤
1.下载image

`docker pull binzhouchn/masr:1.6.0-cuda10.1-cudnn7`

2.运行项目：
`docker run -d -p 5005:5005 -v C:\Users\xiaow\Desktop\a\masr:/workspace/masr  -w /workspace/masr binzhouchn/masr:1.6.0-cuda10.1-cudnn7 gunicorn -b :5005 masr_server:app`

因为使用windows 运行，去掉sudo，同时去掉$pwd,改为绝对路径

3.错误结果如图
![image](https://user-images.githubusercontent.com/17614992/112497017-2c377000-8dc0-11eb-8282-888a14f6c9cc.png)

**Comment by yeyupiaoling** [comment]
@BleethNie windows下的docker可以用GPU吗？

**Comment by BleethNie** [comment]
windows上Docker无法使用GPU

**Comment by binzhouchn** [comment]
@BleethNie 用nvidia-docker

**Comment by qq846511277** [comment]
我是这么安装的
sudo nvidia-docker run -d -p 15005:5005 -v $PWD/masr:/workspace/masr -w /workspace/masr --name masr binzhouchn/masr:1.6.0-cuda10.1-cudnn7 gunicorn -b :5005 masr_server:app

这是我的报错信息，我确实使用了nvidia-docker
[2024-03-22 03:27:23 +0000] [1] [INFO] Starting gunicorn 20.0.4
[2024-03-22 03:27:23 +0000] [1] [INFO] Listening at: http://0.0.0.0:5005 (1)
[2024-03-22 03:27:23 +0000] [1] [INFO] Using worker: sync
[2024-03-22 03:27:23 +0000] [9] [INFO] Booting worker with pid: 9
[2024-03-22 03:27:23 +0000] [9] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/opt/conda/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/opt/conda/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/conda/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/conda/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/opt/conda/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/opt/conda/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/opt/conda/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'masr_server'
[2024-03-22 03:27:23 +0000] [9] [INFO] Worker exiting (pid: 9)
[2024-03-22 03:27:23 +0000] [1] [INFO] Shutting down: Master
[2024-03-22 03:27:23 +0000] [1] [INFO] Reason: Worker failed to boot.
